networks:
  default:
    name: media_network

secrets:
  pihole_password:
    file: ${ROOT_DIR}/secrets/pihole_password.txt

include:
  - compose/compose.network.yaml
  - compose/compose.monitoring.yaml
  - compose/compose.util.yaml
