networks:
  default:
    name: media_network

secrets:
  pihole_password:
    file: ${ROOT_DIR}/secrets/pihole_password.txt
  sonarr_api_key:
    file: ${ROOT_DIR}/secrets/sonarr_api_key.txt
  radarr_api_key:
    file: ${ROOT_DIR}/secrets/radarr_api_key.txt
  prowlarr_api_key:
    file: ${ROOT_DIR}/secrets/prowlarr_api_key.txt
  bazarr_api_key:
    file: ${ROOT_DIR}/secrets/bazarr_api_key.txt

include:
  - compose/compose.network.yaml
  - compose/compose.monitoring.yaml
  - compose/compose.arr.yaml
  - compose/compose.torrent.yaml
  - compose/compose.media.yaml
  - compose/compose.util.yaml
