---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
background:   
  image: https://images.unsplash.com/photo-1673280032614-01ac52a74262?q=80&w=2070&auto=format&fit=crop
  opacity: 50
cardBlur: md
layout:
  - Media:
      icon: mdi-folder-play-outline
      style: row
      columns: 2
  - Arr:
      icon: mdi-cloud-download-outline
      style: row
      columns: 2
  - Web:
      icon: mdi-web
      style: row
      columns: 2
  - Monitoring:
      icon: mdi-eye-outline
      style: row
      columns: 2
iconStyle: theme
useEqualHeights: true
headerStyle: boxed
# showStats: true