---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
background: 
  image: https://images.unsplash.com/photo-1721733258410-35e699661ad6?q=80&w=1740&auto=format&fit=crop
  blur: md
  saturate: 50