services:
  jellyfin:
    image: ghcr.io/hotio/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    env_file:
      - ${ROOT_DIR}/env/shared.env
    environment:
      JELLYFIN_PublishedServerUrl: http://media.${DOMAIN}
    volumes:
      - ${ROOT_DIR}/config/jellyfin:/config
      - ${ROOT_DIR}/data/media:/data/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`media.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    healthcheck:
      test: curl -f http://localhost:8096/health || exit 1
    depends_on:
      traefik:
        condition: service_healthy
        restart: true
  seerr:
    image: ghcr.io/seerr-team/seerr
    container_name: seerr
    restart: unless-stopped
    env_file:
      - ${ROOT_DIR}/env/shared.env
    volumes:
      - ${ROOT_DIR}/config/seerr:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seerr.rule=Host(`seerr.${DOMAIN}`)"
      - "traefik.http.routers.seerr.entrypoints=web"
      - "traefik.http.services.seerr.loadbalancer.server.port=5055"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
