services:
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: unless-stopped
    network_mode: none
    env_file:
      - ${ROOT_DIR}/env/shared.env
      - ${ROOT_DIR}/env/autoheal.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
