services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    env_file:
      - ${ROOT_DIR}/env/shared.env
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --ping=true
    ports:
      - "${TAILSCALE_IP}:80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=80"
    healthcheck:
      test: [ "CMD", "traefik", "healthcheck", "--ping" ]
  pihole:
    # https://docs.pi-hole.net/docker/
    image: pihole/pihole:latest
    container_name: pihole
    hostname: server # For display in UI
    restart: unless-stopped
    env_file:
      - ${ROOT_DIR}/env/shared.env
    secrets:
      - pihole_password
    environment:
      FTLCONF_dns_upstreams: "${LOCAL_IP}#5053" # Local dnscrypt-proxy service
      WEBPASSWORD_FILE: pihole_password
      # When using bridge networking, allow to respond to queries on local network
      FTLCONF_dns_listeningMode: "ALL"
      # Needed here because Tailscale's MagicDNS doesn't work with subdomains, so "service.${DOMAIN}" won't resolve
      FTLCONF_misc_dnsmasq_lines: "address=/${DOMAIN}/${TAILSCALE_IP}"
      FTLCONF_webserver_domain: 'pihole.${DOMAIN}'
      FTLCONF_webserver_session_timeout: 604800 # 1 week
      # For displaying tailscale hostnames in the Pi-hole dashboard
      FTLCONF_dns_hosts: "${TAILNET_HOSTS}" 
      # Disable logging noise due to dnscrypt-proxy upstream
      # See here https://github.com/pi-hole/pi-hole/issues/6079
      FTLCONF_misc_hide_connection_error: false 
    ports:
      # DNS Ports
      - "${LOCAL_IP}:53:53/tcp"
      - "${LOCAL_IP}:53:53/udp"
      - "${TAILSCALE_IP}:53:53/tcp"
      - "${TAILSCALE_IP}:53:53/udp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    volumes:
      - ${ROOT_DIR}/config/pihole:/etc/pihole
    cap_add:
      # See https://docs.pi-hole.net/docker/configuration/#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      #- NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      #- SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.middlewares=pihole-redirect"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.regex=^https?://[^/]+/?$$"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.replacement=http://pihole.${DOMAIN}/admin/"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
