services:
  jellyfin:
    image: ghcr.io/hotio/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    env_file:
      - ${ROOT_DIR}/env/shared.env
    environment:
      JELLYFIN_PublishedServerUrl: http://media.${DOMAIN}
    volumes:
      - ${ROOT_DIR}/config/jellyfin:/config
      - ${ROOT_DIR}/data/media:/data/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`media.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "homepage.group=Media"
      - "homepage.name=Jellyfin"
      - "homepage.icon=jellyfin.png"
      - "homepage.href=http://media.${DOMAIN}/"
      - "homepage.description=Media server for streaming movies and TV shows"
      - "homepage.widget.type=jellyfin"
      - "homepage.widget.url=http://jellyfin:8096"
      - "homepage.widget.key={{HOMEPAGE_FILE_JELLYFIN_KEY}}"
      - "homepage.widget.fields=[\"movies\", \"series\", \"episodes\"]"
      - "homepage.widget.version=2"
      - "homepage.widget.enableBlocks=true"
      - "homepage.widget.showEpisodeNumber=true"
      - "homepage.widget.expandOneStreamToTwoRows=false"
    healthcheck:
      test: curl -f http://localhost:8096/health
    depends_on:
      traefik:
        condition: service_healthy
        restart: true
  seerr:
    image: ghcr.io/seerr-team/seerr
    container_name: seerr
    restart: unless-stopped
    env_file:
      - ${ROOT_DIR}/env/shared.env
    volumes:
      - ${ROOT_DIR}/config/seerr:/app/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seerr.rule=Host(`seerr.${DOMAIN}`)"
      - "traefik.http.routers.seerr.entrypoints=web"
      - "traefik.http.services.seerr.loadbalancer.server.port=5055"
      - "homepage.group=Media"
      - "homepage.name=Seerr"
      - "homepage.icon=seerr.png"
      - "homepage.href=http://seerr.${DOMAIN}/"
      - "homepage.description=Media request management and tracking tool"
      - "homepage.widget.type=seerr"
      - "homepage.widget.url=http://seerr:5055"
      - "homepage.widget.key={{HOMEPAGE_FILE_SEERR_KEY}}"
      - "homepage.widget.fields=[\"pending\", \"approved\", \"completed\", \"issues\"]"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public
