services:
  portainer:
    # Alpine needed here for healthcheck with wget to work
    image: portainer/portainer-ce:alpine-sts
    container_name: portainer
    restart: always
    env_file:
      - ${ROOT_DIR}/env/shared.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT_DIR}/config/portainer:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "homepage.group=Monitoring"
      - "homepage.name=Portainer"
      - "homepage.icon=portainer-alt.png"
      - "homepage.href=http://portainer.${DOMAIN}/"
      - "homepage.description=Container management interface"
    healthcheck:
      test: "wget --no-verbose --tries=3 --spider http://localhost:9000/api/system/status"
  glances:
    # https://github.com/nicolargo/glances/blob/master/docker-compose/docker-compose.yml
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: always
    pid: host
    read_only: true
    privileged: false
    env_file:
      - ${ROOT_DIR}/env/shared.env
      - ${ROOT_DIR}/env/glances.env
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${ROOT_DIR}/config/glances:/glances/conf
      - /etc/os-release:/etc/os-release:ro
    tmpfs:
      - /tmp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`glances.${DOMAIN}`)"
      - "traefik.http.routers.glances.entrypoints=web"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
      - "homepage.group=Monitoring"
      - "homepage.name=Glances"
      - "homepage.icon=glances.png"
      - "homepage.href=http://glances.${DOMAIN}/"
      - "homepage.description=System monitoring tool"
    healthcheck:
      test: "curl -f http://localhost:61208/api/4/status"
  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    restart: unless-stopped
    env_file:
      - ${ROOT_DIR}/env/shared.env
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "home.${DOMAIN}"
    volumes:
      - ${ROOT_DIR}/config/homepage:/app/config
      - ${ROOT_DIR}/config/homepage/icons:/app/public/icons
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.${DOMAIN}`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    depends_on:
      traefik:
        condition: service_healthy
        restart: true
      dockerproxy:
        condition: service_healthy
        restart: true
