services:
  bittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: bittorrent
    restart: unless-stopped
    env_file:
      - ${ROOT_DIR}/env/shared.env
    volumes:
      - ${ROOT_DIR}/config/bittorrent:/config
      - ${ROOT_DIR}/data/torrents:/data/torrents
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bittorrent.rule=Host(`torrent.${DOMAIN}`)"
      - "traefik.http.routers.bittorrent.entrypoints=web"
      - "traefik.http.services.bittorrent.loadbalancer.server.port=8080"
      - "homepage.group=Arr"
      - "homepage.name=qBittorrent"
      - "homepage.icon=qbittorrent.png"
      - "homepage.href=http://torrent.${DOMAIN}/"
      - "homepage.description=BitTorrent client"
      - "homepage.weight=4"
    healthcheck:
      test: curl -f http://localhost:8080
    depends_on:
      traefik:
        condition: service_healthy
        restart: true
